### ISSUE TITLE
Error censys and zoomeye

### ISSUE THREAD

**Issue by lolminerxmrig** [saucer-man/tget#9]
Hi.

plz help fixed Error :

python3 tget.py censys "services.http.response.favicons.md5_hash="1c5857ecc888208a1c1eb0f73c052391""  -v --limit 1000 -o result.txt

![image](https://github.com/saucer-man/tget/assets/108659226/a6e7e6ca-668a-4cb0-8427-9b5f264df589)

**Comment by lolminerxmrig** [comment]
python3 tget.py zoomeye -d "title:WSO2 Management Console" -v --limit 3000 --type host -o result.txt

![image](https://github.com/saucer-man/tget/assets/108659226/bdbb9ab3-add3-41cf-8807-c25b13d0d83f)

**Comment by saucer-man** [comment]
pip install -r requirements.txt

**Comment by lolminerxmrig** [comment]
yes , not work.

**Comment by saucer-man** [comment]
show your censys version, my local version is 2.1.9
